**Problem 1**

Import Numpy as np

In [1]:
import numpy as np


**Problem 2**

Create a 1D array of numbers from 0 to 9.

In [19]:
array1 = np.array([0,1,2,3,4,5,6,7,8,9])
print (array1)

[0 1 2 3 4 5 6 7 8 9]


**Problem 3**

Create a 3×3 numpy array of all True’s.

In [21]:
#array3 = np.array([[True,True,True],[True,True,True],[True,True,True]])
array3 = np.array([[True]*3]*3)
print(array3)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**Problem 4**

Extract all odd numbers from arr.

In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd_array = arr[arr %2 == 1]
print(odd_array)

[1 3 5 7 9]


**Problem 5**

Replace all odd numbers in arr with -1.

In [22]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
#neg_array = np.where(arr %2 == 1, arr ,-1)
#print(neg_array)
arr[arr %2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1 -1]


**Problem 6**

Convert a 1D array to a 2D array with 2 rows.

In [12]:
arr = np.arange(10).reshape(2,5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


**Problem 7** 

Stack arrays a and b vertically.

In [16]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)
np.vstack((a,b))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**Problem 8**

Stack the arrays a and b horizontally.

In [18]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)
np.hstack((a,b))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

**Problem 9**

Get the common items between a and b.

In [23]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


**Problem 10**

From array a remove all items present in array b

In [27]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(np.setdiff1d(a,b))

[1 2 3 4]


**Problem 11**

Get the positions where elements of a and b match

In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# find the common elements
common_elements = np.intersect1d(a, b)
print(common_elements)

# find the indices of the common elements in array1
indices = np.where(np.in1d(a, common_elements))

print(indices)

[2 4]
(array([1, 3, 5, 7], dtype=int64),)


**Problem 12** 

Get all items between 5 and 10 from a.

In [34]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
#items = np.where(np.logical_and(a>5,a<10))
result = a[(a>5)*(a<10)]
  
print(result)

[6 9]


**Problem 13**

Swap columns 1 and 2 in the array arr.

In [37]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:,[2,0]] = arr[:,[0,2]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


**Problem 14**

Swap rows 1 and 2 in the array arr.

In [39]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[[1,0]] = arr[[0,1]]
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


**Problem 15**

Reverse the rows of a 2D array arr.

In [ ]:
arr = np.arange(9).reshape(3,3)

**Problem 16**

Reverse the columns of a 2D array arr.

In [40]:
arr = np.arange(9).reshape(3,3)
arr2 = np.fliplr(arr)
print(arr)
print(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


**Problem 17**

Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

In [42]:
rand = np.random.uniform(size = (5, 3),low = 5,high = 10)
print (rand)


[[9.70217659 7.19328054 8.83405573]
 [5.30461858 9.27710077 7.71061896]
 [9.31430084 6.50622209 7.62562856]
 [9.29076954 9.52292426 7.82266389]
 [7.05995942 9.9654867  7.84861749]]


**Problem 18**

Print or show only 3 decimal places of the numpy array rand_arr.

In [45]:
rand = np.random.uniform(size=(2,2))
print (rand)
np.set_printoptions(precision=3)
print(rand)

[[0.13411971 0.33359875]
 [0.94530168 0.49461748]]
[[0.134 0.334]
 [0.945 0.495]]
